### PR TITLE
Dp 1332 Expanded Comparison file

### PR DESCRIPTION
**Pull request by JordanBalesBAO**
### Related Issues
- DP-XXX
- etc.

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

### CODE REVIEW

**Comment by JordanBalesBAO** [comment]
Note DP-1332 datapackr needs to be installed to test

**Review by flopez-bao — APPROVED** [review]

**Comment by JordanBalesBAO** [comment]
dont merge until datapackr is released

**Comment by jason-p-pickering** [comment]
@JordanBalesBAO I think we should probably add a new event for the analytics report using something like 

```
sendEventToS3(d, "COMPARISON_PLUS")
```

Maybe we should clean this up in another ticket though?

**Review by jason-p-pickering — CHANGES_REQUESTED** [review]
See my comment regarding the download event which I think we should add to the new download type.

**Comment by JordanBalesBAO** [comment]
@jason-p-pickering Ran through the code and I see where we do a combo of sendEventToS3 & observeEvent.  However the only download type we don't do that for is comparison. Not sure of the reasoning other than maybe clutter, but should we do it for comparison plus if we don't for comparison?

**Comment by JordanBalesBAO** [comment]
Ready for another look @jason-p-pickering

**Comment by JordanBalesBAO** [comment]
reminder do not merge until datapackr is released

**Pull request merged**
